title: Charming
description: Documentation for the Charming Ruby gem.
theme: just-the-docs
color_scheme: synthwave

url: https://pandorocks.github.io

aux_links:
  Charming on GitHub: https://github.com/pandorocks/charming
